import { StyleSheet } from "@react-pdf/renderer";

/** Charte Sia / AZ (couleurs sobres, accent navy + amber). */
export const COLORS = {
  navy: "#0B2A4A",
  blue: "#1E5A8A",
  amber: "#C9821B",
  text: "#1A1A1A",
  muted: "#6B7280",
  line: "#E2E6EB",
  bgSoft: "#F4F6F8",
  red: "#B91C1C",
  green: "#166534",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 36,
    paddingBottom: 44,
    paddingHorizontal: 40,
    fontSize: 10,
    color: COLORS.text,
    fontFamily: "Helvetica",
  },
  headerBand: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    borderBottomWidth: 2,
    borderBottomColor: COLORS.navy,
    paddingBottom: 8,
    marginBottom: 16,
  },
  brand: { fontSize: 9, color: COLORS.blue, fontFamily: "Helvetica-Bold", letterSpacing: 1 },
  docTitle: { fontSize: 18, color: COLORS.navy, fontFamily: "Helvetica-Bold" },
  docMeta: { fontSize: 8, color: COLORS.muted, textAlign: "right" },
  h2: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: COLORS.navy,
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  badgeRow: { flexDirection: "row", flexWrap: "wrap", gap: 5, marginTop: 4 },
  badge: {
    fontSize: 8,
    color: "#FFFFFF",
    backgroundColor: COLORS.blue,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 3,
  },
  kpiRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 6 },
  kpi: {
    width: "31%",
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 4,
    padding: 6,
  },
  kpiLabel: { fontSize: 7, color: COLORS.muted, textTransform: "uppercase" },
  kpiValue: { fontSize: 13, fontFamily: "Helvetica-Bold", color: COLORS.navy, marginTop: 2 },
  nbaBox: {
    borderWidth: 1,
    borderColor: COLORS.amber,
    backgroundColor: "#FCF6EC",
    borderRadius: 4,
    padding: 8,
    marginTop: 6,
  },
  nbaTitle: { fontSize: 10, fontFamily: "Helvetica-Bold", color: COLORS.amber },
  body: { fontSize: 9.5, lineHeight: 1.4, color: COLORS.text },
  row: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: COLORS.line, paddingVertical: 3 },
  rowHead: { flexDirection: "row", borderBottomWidth: 1, borderBottomColor: COLORS.navy, paddingVertical: 3 },
  cell: { fontSize: 9 },
  cellHead: { fontSize: 8, fontFamily: "Helvetica-Bold", color: COLORS.navy, textTransform: "uppercase" },
  muted: { color: COLORS.muted },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: COLORS.muted,
    borderTopWidth: 1,
    borderTopColor: COLORS.line,
    paddingTop: 4,
  },
});
